# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bigdecimal` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

class BigDecimal < ::Numeric
  extend ::BigDecimal::Deprecation

  def to_d; end
  def to_digits; end

  class << self
    def inherited(subclass); end
  end
end

module BigDecimal::Deprecation
  def new(*args, **kwargs); end
end

BigDecimal::EXCEPTION_NaN = T.let(T.unsafe(nil), Integer)
BigDecimal::VERSION = T.let(T.unsafe(nil), String)

class NilClass
  include ::JSON::Ext::Generator::GeneratorMethods::NilClass

  def to_d; end
end
