# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `database_cleaner-sequel` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module DatabaseCleaner
  class << self
    def [](*args, &block); end
    def allow_production; end
    def allow_production=(_arg0); end
    def allow_remote_database_url; end
    def allow_remote_database_url=(_arg0); end
    def clean(*args, &block); end
    def clean_with(*args, &block); end
    def cleaners; end
    def cleaners=(_arg0); end
    def cleaning(*args, &block); end
    def start(*args, &block); end
    def strategy=(*args, &block); end
    def url_allowlist; end
    def url_allowlist=(_arg0); end
    def url_whitelist; end
    def url_whitelist=(_arg0); end
  end
end

module DatabaseCleaner::Sequel; end

class DatabaseCleaner::Sequel::Base < ::DatabaseCleaner::Strategy
  def db; end
end

class DatabaseCleaner::Sequel::Deletion < ::DatabaseCleaner::Sequel::Truncation
  def clean; end
  def delete_tables(db, tables); end
  def disable_referential_integrity(tables); end
end

class DatabaseCleaner::Sequel::Transaction < ::DatabaseCleaner::Sequel::Base
  def clean; end
  def start; end
end

class DatabaseCleaner::Sequel::Truncation < ::DatabaseCleaner::Sequel::Base
  def initialize(only: T.unsafe(nil), except: T.unsafe(nil), pre_count: T.unsafe(nil)); end

  def clean; end
  def start; end

  private

  def dirty?; end
  def migration_storage_names; end
  def pre_count?; end
  def pre_count_tables(tables); end
  def tables_to_truncate(db); end
  def truncate_tables(db, tables); end
  def txid; end
end

DatabaseCleaner::Sequel::VERSION = T.let(T.unsafe(nil), String)
DatabaseCleaner::VERSION = T.let(T.unsafe(nil), String)
