# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `hanami-webconsole` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Hanami
  class << self
    def app; end
    def app?(app); end
    def boot; end
    def code_reloading?; end
    def configuration; end
    def configure(&blk); end
    def env; end
    def env?(*names); end
    def environment; end
    def logger; end
    def plugin(&blk); end
    def plugins; end
    def public_directory; end
    def root; end
  end
end

Hanami::DEFAULT_PUBLIC_DIRECTORY = T.let(T.unsafe(nil), String)
Hanami::VERSION = T.let(T.unsafe(nil), String)
module Hanami::Webconsole; end
Hanami::Webconsole::VERSION = T.let(T.unsafe(nil), String)
