# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `hanami-helpers` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Hanami
  class << self
    def app; end
    def app?(app); end
    def boot; end
    def code_reloading?; end
    def configuration; end
    def configure(&blk); end
    def env; end
    def env?(*names); end
    def environment; end
    def logger; end
    def plugin(&blk); end
    def plugins; end
    def public_directory; end
    def root; end
  end
end

Hanami::DEFAULT_PUBLIC_DIRECTORY = T.let(T.unsafe(nil), String)
module Hanami::Helpers; end

module Hanami::Helpers::HtmlHelper
  private

  def html(&blk); end
end

class Hanami::Helpers::HtmlHelper::EmptyHtmlNode
  def initialize(name, attributes); end

  def to_s; end

  private

  def attribute(attribute_name, value); end
  def attributes; end
  def boolean_attribute(attribute_name, _value); end
  def boolean_attribute?(attribute_name); end
  def prepare_html_attributes(attributes); end
end

Hanami::Helpers::HtmlHelper::EmptyHtmlNode::ATTRIBUTES_SEPARATOR = T.let(T.unsafe(nil), String)
Hanami::Helpers::HtmlHelper::EmptyHtmlNode::BOOLEAN_ATTRIBUTES = T.let(T.unsafe(nil), Array)

class Hanami::Helpers::HtmlHelper::HtmlBuilder
  include ::Hanami::Utils::ClassAttribute
  extend ::Hanami::Utils::ClassAttribute::ClassMethods

  def initialize; end

  def +(content); end
  def a(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def abbr(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def address(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def area(attributes = T.unsafe(nil)); end
  def article(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def aside(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def audio(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def b(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def base(attributes = T.unsafe(nil)); end
  def bdi(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def bdo(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def blockquote(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def body(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def br(attributes = T.unsafe(nil)); end
  def button(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def canvas(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def caption(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def cite(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def code(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def col(attributes = T.unsafe(nil)); end
  def colgroup(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def data(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def datalist(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def dd(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def del(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def details(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def dfn(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def dialog(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def div(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def dl(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def dt(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def em(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def embed(attributes = T.unsafe(nil)); end
  def empty_tag(name, attributes = T.unsafe(nil)); end
  def encode(encoding); end
  def fieldset(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def figcaption(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def figure(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def footer(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def form(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def fragment(&blk); end
  def h1(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def h2(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def h3(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def h4(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def h5(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def h6(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def head(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def header(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def hgroup(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def hr(attributes = T.unsafe(nil)); end
  def i(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def iframe(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def img(attributes = T.unsafe(nil)); end
  def input(attributes = T.unsafe(nil)); end
  def ins(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def kbd(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def keygen(attributes = T.unsafe(nil)); end
  def label(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def legend(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def li(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def link(attributes = T.unsafe(nil)); end
  def main(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def map(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def mark(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def math(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def menu(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def menuitem(attributes = T.unsafe(nil)); end
  def meta(attributes = T.unsafe(nil)); end
  def meter(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def method_missing(method_name, *args, &blk); end
  def nav(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def nested?; end
  def noscript(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def object(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def ol(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def optgroup(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def option(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def options; end
  def output(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def p(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def param(attributes = T.unsafe(nil)); end
  def pre(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def progress(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def q(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def resolve(&blk); end
  def rp(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def rt(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def rtc(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def ruby(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def s(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def samp(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def script(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def section(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def select(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def slot(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def small(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def source(attributes = T.unsafe(nil)); end
  def span(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def strong(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def style(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def sub(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def summary(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def sup(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def svg(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def table(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def tag(name, content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def tbody(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def td(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def template(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def text(content); end
  def textarea(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def tfoot(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def th(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def thead(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def time(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def title(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def to_s; end
  def tr(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def track(attributes = T.unsafe(nil)); end
  def u(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def ul(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def var(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def video(content = T.unsafe(nil), attributes = T.unsafe(nil), &blk); end
  def wbr(attributes = T.unsafe(nil)); end

  private

  def respond_to_missing?(method_name, include_all); end

  class << self
    def html_node; end
    def html_node=(_arg0); end
  end
end

Hanami::Helpers::HtmlHelper::HtmlBuilder::CONTENT_TAGS = T.let(T.unsafe(nil), Array)
Hanami::Helpers::HtmlHelper::HtmlBuilder::EMPTY_TAGS = T.let(T.unsafe(nil), Array)
Hanami::Helpers::HtmlHelper::HtmlBuilder::NEWLINE = T.let(T.unsafe(nil), String)

class Hanami::Helpers::HtmlHelper::HtmlFragment
  def initialize(&blk); end

  def content; end
  def to_s; end
end

class Hanami::Helpers::HtmlHelper::HtmlNode < ::Hanami::Helpers::HtmlHelper::EmptyHtmlNode
  def initialize(name, content, attributes, _options = T.unsafe(nil)); end

  def to_s; end

  private

  def content; end
end

class Hanami::Helpers::HtmlHelper::TextNode
  def initialize(content); end

  def to_s; end
end

Hanami::VERSION = T.let(T.unsafe(nil), String)
