# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `inflecto` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Inflecto
  class << self
    def camelize(input); end
    def classify(table_name); end
    def constantize(input); end
    def dasherize(input); end
    def demodulize(input); end
    def foreign_key(input); end
    def humanize(input); end
    def inflections; end
    def ordinalize(number); end
    def pluralize(word); end
    def singularize(word); end
    def tableize(input); end
    def underscore(input); end
  end
end

class Inflecto::Inflections
  def initialize; end

  def clear; end
  def human(rule, replacement); end
  def humans; end
  def irregular(singular, plural); end
  def plural(rule, replacement); end
  def plurals; end
  def singular(rule, replacement); end
  def singulars; end
  def uncountable(words); end
  def uncountables; end

  class << self
    def instance; end
  end
end
