# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `pry-remote` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

class Object < ::BasicObject
  include ::Kernel
  include ::JSON::Ext::Generator::GeneratorMethods::Object
  include ::PP::ObjectMixin

  def pry_remote(host = T.unsafe(nil), port = T.unsafe(nil), options = T.unsafe(nil)); end
  def remote_pry(host = T.unsafe(nil), port = T.unsafe(nil), options = T.unsafe(nil)); end
end

module PryRemote; end

class PryRemote::CLI
  def initialize(args = T.unsafe(nil)); end

  def capture; end
  def capture?; end
  def host; end
  def port; end
  def run(input = T.unsafe(nil), output = T.unsafe(nil)); end
  def uri; end
  def wait; end
  def wait?; end
end

class PryRemote::Client < ::Struct
  def input; end
  def input=(_); end
  def input_proxy; end
  def kill; end
  def output; end
  def output=(_); end
  def stderr; end
  def stderr=(_); end
  def stdout; end
  def stdout=(_); end
  def thread; end
  def thread=(_); end
  def wait; end

  class << self
    def [](*_arg0); end
    def inspect; end
    def members; end
    def new(*_arg0); end
  end
end

PryRemote::DefaultHost = T.let(T.unsafe(nil), String)
PryRemote::DefaultPort = T.let(T.unsafe(nil), Integer)

class PryRemote::IOUndumpedProxy
  include ::DRb::DRbUndumped

  def initialize(obj); end

  def <<(data); end
  def completion_proc; end
  def completion_proc=(val); end
  def print(*objs); end
  def printf(*args); end
  def puts(*lines); end
  def readline(prompt); end
  def tty?; end
  def write(data); end
end

class PryRemote::InputProxy < ::Struct
  def completion_proc=(val); end
  def input; end
  def input=(_); end
  def readline(prompt); end
  def readline_arity; end

  class << self
    def [](*_arg0); end
    def inspect; end
    def members; end
    def new(*_arg0); end
  end
end

class PryRemote::Server
  def initialize(object, host = T.unsafe(nil), port = T.unsafe(nil), options = T.unsafe(nil)); end

  def client; end
  def host; end
  def object; end
  def port; end
  def run; end
  def setup; end
  def teardown; end
  def uri; end

  class << self
    def run(object, host = T.unsafe(nil), port = T.unsafe(nil), options = T.unsafe(nil)); end
  end
end

PryRemote::System = T.let(T.unsafe(nil), Proc)
