# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubocop-sequel/all/rubocop-sequel.rbi
#
# rubocop-sequel-0.2.0

module RuboCop
end
module RuboCop::Cop
end
module RuboCop::Cop::Sequel
end
class RuboCop::Cop::Sequel::ColumnDefault < RuboCop::Cop::Base
  def add_column_default?(param0 = nil); end
  def on_send(node); end
end
class RuboCop::Cop::Sequel::ConcurrentIndex < RuboCop::Cop::Base
  def indexes?(param0 = nil); end
  def offensive?(args); end
  def on_send(node); end
end
class RuboCop::Cop::Sequel::JSONColumn < RuboCop::Cop::Base
  def column_method?(param0 = nil); end
  def column_type?(param0 = nil); end
  def json_or_hstore?(param0 = nil); end
  def on_block(node); end
  def on_send(node); end
end
class RuboCop::Cop::Sequel::MigrationName < RuboCop::Cop::Base
  def filename_bad?(path); end
  def on_new_investigation; end
  include RuboCop::Cop::RangeHelp
end
class RuboCop::Cop::Sequel::SaveChanges < RuboCop::Cop::Base
  def model_save?(param0 = nil); end
  def on_send(node); end
  extend RuboCop::Cop::AutoCorrector
end
