# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/squasher/all/squasher.rbi
#
# squasher-0.6.2

module Squasher
  def ask(*args); end
  def clean; end
  def colorize(message); end
  def config; end
  def error(*args); end
  def messages; end
  def print(message, options = nil); end
  def rake(command, description = nil); end
  def setup(options); end
  def squash(raw_date); end
  def tell(key, options = nil); end
  extend Squasher
end
class Squasher::Config
  def dbconfig; end
  def dbconfig?; end
  def dbconfig_file; end
  def in_app_root(&block); end
  def initialize; end
  def migration_file(timestamp, migration_name); end
  def migration_files; end
  def migration_version; end
  def migrations_folder; end
  def migrations_folder?; end
  def schema_file; end
  def set(key, value); end
  def set?(k); end
  def set_app_path(path); end
  def stub_dbconfig; end
end
module Squasher::Config::Render
  def const_missing(*args); end
  def inspect; end
  def method_missing(*args); end
  def process(path); end
  def to_s; end
  extend Squasher::Config::Render
end
