# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `trailblazer` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

module Trailblazer
  class << self
    def Context(wrapped_options, mutable_options = T.unsafe(nil), context_options = T.unsafe(nil)); end
    def Operation(options); end
    def Option(proc); end
  end
end

module Trailblazer::Version; end
Trailblazer::Version::VERSION = T.let(T.unsafe(nil), String)
