# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/trailblazer-macro-contract/all/trailblazer-macro-contract.rbi
#
# trailblazer-macro-contract-2.1.1

module Trailblazer
end
module Trailblazer::Macro
end
module Trailblazer::Macro::Contract
  def self.Build(name: nil, constant: nil, builder: nil); end
  def self.Persist(method: nil, name: nil); end
  def self.Validate(skip_extract: nil, name: nil, representer: nil, key: nil, constant: nil, invalid_data_terminus: nil); end
end
module Trailblazer::Macro::Contract::Build
  def self.call(options, circuit_options, name: nil, constant: nil, builder: nil); end
  def self.call_builder(ctx, circuit_options, builder: nil, constant: nil, name: nil); end
end
module Trailblazer::Macro::Contract::DSL
  def contract(name = nil, constant = nil, base: nil, &block); end
  def self.extended(extender); end
end
class Trailblazer::Macro::Contract::Validate
  def call(ctx, **arg1); end
  def initialize(name: nil, representer: nil, params_path: nil, constant: nil); end
  def validate!(options, representer: nil, from: nil, params_path: nil); end
end
class Trailblazer::Macro::Contract::Validate::Extract
  def call(ctx, params: nil, **arg2); end
  def initialize(key: nil, params_path: nil); end
end
module Trailblazer::Activity::DSL::Linear::Helper
end
module Trailblazer::Version
end
module Trailblazer::Version::Macro
end
module Trailblazer::Version::Macro::Contract
end
