# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `url_mount` gem.
# Please instead update this file by running `bin/tapioca sync`.

# typed: true

class UrlMount
  def initialize(path, opts = T.unsafe(nil), &blk); end

  def callback(&blk); end
  def defaults; end
  def defaults=(_arg0); end
  def host; end
  def host=(_arg0); end
  def local_segments; end
  def optional_variable_segments; end
  def optional_variables; end
  def options; end
  def options=(_arg0); end
  def raw_path; end
  def raw_path=(_arg0); end
  def required_variable_segments; end
  def required_variables; end
  def scheme; end
  def scheme=(_arg0); end
  def to_s(env = T.unsafe(nil), opts = T.unsafe(nil)); end
  def url(env = T.unsafe(nil), opts = T.unsafe(nil)); end
  def url_mount; end
  def url_mount=(_arg0); end
  def variables; end

  private

  def local_required_variables; end
  def parse_local_segments; end
  def required_to_generate?; end
end

UrlMount::DELIMETERS = T.let(T.unsafe(nil), Array)
class UrlMount::Segment; end

class UrlMount::Segment::Base
  def name; end
  def name=(_arg0); end
  def optional_variable_segments; end
  def required_variable_segments; end
end

class UrlMount::Segment::Conditional < ::UrlMount::Segment::Base
  def initialize(*args); end

  def optional_variable_segments; end
  def optional_variables; end
  def required_variables; end
  def to_s(opts = T.unsafe(nil)); end
end

class UrlMount::Segment::Conditional::UnrequiredUrlMount < ::UrlMount
  private

  def required_to_generate?; end
end

class UrlMount::Segment::Delimeter < ::UrlMount::Segment::Base
  def to_s(opts = T.unsafe(nil)); end
end

class UrlMount::Segment::Static < ::UrlMount::Segment::Base
  def initialize(name); end

  def to_s(opts = T.unsafe(nil)); end
end

class UrlMount::Segment::Variable < ::UrlMount::Segment::Base
  def initialize(name, options); end

  def required_variable_segments; end
  def to_s(opts = T.unsafe(nil)); end
end

class UrlMount::Ungeneratable < ::StandardError; end
